site_name: Docs Finder
site_url: https://github.com/docsfinder/docsfinder
repo_url: https://github.com/docsfinder/docsfinder
edit_uri: "https://github.com/docsfinder/docsfinder"/edit/main/docs

theme:
  name: material
  language: en
  features:
    - navigation.instant
  palette:
    primary: black
    accent: light blue

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: 🔗

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/codestrange
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/docsfinder
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/codestrange
      name: Twitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/codestrange
      name: Telegram
    - icon: fontawesome/solid/paper-plane
      link: mailto:codestrangeofficial@gmail.com
      name: Email
