site_name: Docs Finder
site_url: https://github.com/docsfinder/docsfinder
repo_url: https://github.com/docsfinder/docsfinder
edit_uri: "https://github.com/docsfinder/docsfinder"/edit/main/docs

theme:
  name: material
  language: en
  features:
    - navigation.instant
  palette:
    primary: black
    accent: light blue

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: 🔗

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/codestrange
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/docsfinder
      name: GitHub
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/codestrange
      name: GitLab
    - icon: fontawesome/solid/code
      link: https://profile.codersrank.io/user/codestrange
      name: Codersrank
    - icon: fontawesome/brands/dev
      link: https://dev.to/codestrange
      name: Dev.to
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/8921443/codestrange
      name: Stack Overflow
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/codestrange
      name: Research Gate
    - icon: fontawesome/brands/medium
      link: https://medium.com/@codestrange
      name: Medium
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/codestrange
      name: Twitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/codestrange
      name: Telegram
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/codestrange
      name: Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/codestrange
      name: Instagram
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/codestrange
      name: Youtube
    - icon: fontawesome/solid/paper-plane
      link: mailto:codestrangeofficial@gmail.com
      name: Email
